In [ ]:

import numpy as np
#1. Initialize an empty array with size 2X2.
arr1= np.empty((2,2))
print(arr1.shape)


#2. Initialize an all one array with size 4X2.
arr2= np.ones((4,2))
print(arr2)


#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
arr3 = np.full((3, 3), 7)
print(arr3)


#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
a = np.array([[1, 2], [3, 4]])
arr4 = np.zeros_like(a)
print(arr4)


#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
a1 = np.array([[1, 2], [3, 4]])   # given array
arr5 = np.ones_like(a1)
print(arr5)


#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}
new_list = [1, 2, 3, 4]
arr6 = np.array(new_list)
print(arr6)

(2, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


In [ ]:
import numpy as np


#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
array1= np.arange(10,50)
print(array1)


#2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}
array2= np.arange(9)
arr2= array2.reshape(3,3)
print(arr2)


#3. Create a 3X3 identity matrix.{Hint:np.eye()}
array3= np.eye(3)
print(array3)


#4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
array4= np.random.random(30)
mean_values= array4.mean()
print(f"the mean value is {mean_values}")


#5. Create a 10X10 array with random values and find the minimum and maximum values.
array5= np.random.random((10,10))
max= array5.max()
min= array5.min()
print(f"maximum value is: {max}")
print(f"minimum value is: {min}")

#6. Create a zero array of size 10 and replace 5th element with 1.
array6= np.zeros(10)
array6[4]=1
print(array6)


#7. Reverse an array arr = [1,2,0,0,4,0].
arr= [1,2,0,0,4,0]
array7= np.array(arr)
reversed_array= array7[::-1]
print(f"the reversed array is {reversed_array}")


#8. Create a 2d array with 1 on border and 0 inside.
array8 = np.ones((3,3))
array8[1:2, 1:2] = 0
print(array8)


#9. Create a 8X8 matrix and fill it with a checkerboard pattern.
array9 = np.zeros((8, 8))
array9[1::2, ::2] = 1
array9[::2, 1::2] = 1
print(f"the checker board pattern is: \n {array9}")

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
the mean value is 0.5043509709086773
maximum value is: 0.992825216108046
minimum value is: 0.00408132667318839
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
the reversed array is [0 4 0 0 2 1]
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]
the checker board pattern is: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
from sys import exception
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
#1. Add the two array.
Addition= np.add(x,y)
print(f"the addition of two array is: \n {Addition}")


#2. Subtract the two array.
subtraction= np.subtract(w,v)
print(f"the addition of two array is: \n {subtraction}")


#3. Multiply the array with any integers of your choice.
multiply= y *2
print(f"the multiplication  is: \n {multiply}")


#4. Find the square of each element of the array.
square= np.square(x)
print(f"the square of a array is: \n {square}")


#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
dot_vw= np.dot(v,w)
dot_xv= np.dot(x,v)
dot_xy= np.dot(x,y)
print(f"the dot product between v ad w is: \n {dot_vw}")
print(f"the dot product between x ad v is: \n {dot_xv}")
print(f"the dot product between x ad y is: \n {dot_xy}")


#6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
v_2d = v.reshape(1, -1)
w_2d = w.reshape(1, -1)
concatination_xy_rows = np.vstack((x, y))
print("x and y using vstack:")
print(concatination_xy_rows)

concatination_vw_rows = np.hstack((v_2d, w_2d))
print("\nv and w using hstack:")
print(concatination_vw_rows)


#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
try:
  test = np.concatenate((x, v), axis=0) # Fix: Reshape v to be a 2D row vector (1, N) and concatenate along axis 0
  print("print",test)
except Exception  as e:
  print(" \n the error is ",e)

#we cannot concatinate becuase all the input arrays must have same number of dimensions,
# but the array at index 0 has 2 dimension and the array at index 1 has 1 dimension

the addition of two array is: 
 [[ 6  8]
 [10 13]]
the addition of two array is: 
 [2 2]
the multiplication  is: 
 [[10 12]
 [14 16]]
the square of a array is: 
 [[ 1  4]
 [ 9 25]]
the dot product between v ad w is: 
 219
the dot product between x ad v is: 
 [29 77]
the dot product between x ad y is: 
 [[19 22]
 [50 58]]
x and y using vstack:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

v and w using hstack:
[[ 9 10 11 12]]
 
 the error is  all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]]);

#1. Prove A.A−1 = I.
A_inverse= np.linalg.inv(A)
dot_product= np.dot(A,A_inverse)
print(dot_product)  #it is approximateto [1 0]
#                                        [0 1]


#2. Prove AB ̸= BA.
AB= np.dot(A, B)
BA= np.dot(B, A)
print(f"\n {AB}")
print(f"\n {BA}")
print("hence, AB is not equal to BA")

#3. Prove (AB)^T = B^T*A^T
AB_T = np.dot(A, B).T
BT_AT = np.dot(B.T, A.T)
print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", BT_AT)
print("hence, (AB)^T is not equal to B^T* A^T")


#4 Solve the following system of Linear equation using Inverse Methods.

# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A_matrix = np.array([[2, -3, 1],
                  [1, -1, 2],
                  [3, 1, -1]])
B_matrix = np.array([[-1],
                  [-3],
                  [9]])

A_inverses= np.linalg.inv(A_matrix)
X= np.dot(A_inverses, B_matrix)
print("the values of x,y,z are: \n",X)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

 [[23 13]
 [51 29]]

 [[36 44]
 [13 16]]
hence, AB is not equal to BA
(AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
hence, (AB)^T is not equal to B^T* A^T
the values of x,y,z are: 
 [[ 2.]
 [ 1.]
 [-2.]]
